apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-app
  labels:
    app: kubernetes-demo-app
spec:
  selector:
    app: kubernetes-demo-app
  ports:
    - protocol: TCP
      port: 3000 #service port
      targetPort: 3000 # container port
  type: NodePort # change to load balancer if running in the cloud